/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package penjualan.view;
    import java.sql.SQLDataException;
    import java.util.ArrayList;
    import java.util.logging.Level;
    import java.util.logging.Logger;
    import penjualan.koneksi.koneksi;
    import java.sql.ResultSet;
    import java.sql.Statement;
    import java.text.SimpleDateFormat;
    import java.util.Date;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
    import penjualan.implement.transaksiImplement;
    import java.sql.PreparedStatement;
    import java.sql.SQLException;
    import kasir.MenuUtama;

/**
 *
 * @author rizkiramdani
 */
public final class transaksiView extends javax.swing.JFrame {
    private DefaultTableModel model;
  
    /**
     * Creates new form transaksiView
     */
    public transaksiView() throws SQLException {
        initComponents();
        model = new DefaultTableModel();
        tabelTransaksi.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Subtotal");
        dateNow();
        genFak();
        setKodeBarang();
        setKodePelanggan();
        btTambahtrans.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background31 = new Background.Background3();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JComboBox();
        notlp = new Background.TextFieldTransparan();
        stok = new Background.TextFieldTransparan();
        harga = new Background.TextFieldTransparan();
        jumlah = new Background.TextFieldTransparan();
        nama_barang = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        no_faktur = new Background.TextFieldTransparan();
        tgl_penjualan = new Background.TextFieldTransparan();
        background21 = new Background.Background2();
        btTambahtrans = new Background.ButtonTransparan();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        totalBayar = new Background.TextFieldTransparan();
        background22 = new Background.Background2();
        simpanTransaksi = new Background.ButtonTransparan();
        background23 = new Background.Background2();
        simpanKeranjang = new Background.ButtonTransparan();
        background24 = new Background.Background2();
        hapus = new Background.ButtonTransparan();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        Gambar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Kembali = new Background.ButtonTransparan();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Stok Barang");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Harga");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Jumlah Pembelian");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DATA PELANGGAN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nama Pelanggan");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("No Tlp");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("DATA BARANG");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Nama Barang");

        nama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namaItemStateChanged(evt);
            }
        });

        notlp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        stok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        harga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jumlah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        nama_barang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nama_barang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nama_barangItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("No Faktur");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Tanggal Transaksi");

        no_faktur.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tgl_penjualan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btTambahtrans.setText("Tambah Data Transaksi");
        btTambahtrans.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btTambahtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahtransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background21Layout = new javax.swing.GroupLayout(background21);
        background21.setLayout(background21Layout);
        background21Layout.setHorizontalGroup(
            background21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btTambahtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        background21Layout.setVerticalGroup(
            background21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btTambahtrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Total Pembayaran");

        totalBayar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        simpanTransaksi.setText("Simpan Transaksi");
        simpanTransaksi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        simpanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background22Layout = new javax.swing.GroupLayout(background22);
        background22.setLayout(background22Layout);
        background22Layout.setHorizontalGroup(
            background22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simpanTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
        background22Layout.setVerticalGroup(
            background22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background22Layout.createSequentialGroup()
                .addComponent(simpanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        simpanKeranjang.setText("Simpan Ke Keranjang");
        simpanKeranjang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        simpanKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKeranjangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background23Layout = new javax.swing.GroupLayout(background23);
        background23.setLayout(background23Layout);
        background23Layout.setHorizontalGroup(
            background23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simpanKeranjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        background23Layout.setVerticalGroup(
            background23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background23Layout.createSequentialGroup()
                .addComponent(simpanKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        hapus.setText("Hapus");
        hapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background24Layout = new javax.swing.GroupLayout(background24);
        background24.setLayout(background24Layout);
        background24Layout.setHorizontalGroup(
            background24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        background24Layout.setVerticalGroup(
            background24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background24Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane2.setViewportView(alamat);

        javax.swing.GroupLayout background31Layout = new javax.swing.GroupLayout(background31);
        background31.setLayout(background31Layout);
        background31Layout.setHorizontalGroup(
            background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background31Layout.createSequentialGroup()
                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(background31Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(background22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(background31Layout.createSequentialGroup()
                                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, background31Layout.createSequentialGroup()
                                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(26, 26, 26)
                                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(notlp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(background31Layout.createSequentialGroup()
                                        .addComponent(background23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(background24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background31Layout.createSequentialGroup()
                                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(background31Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10))
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tgl_penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(no_faktur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(background21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(27, 27, 27))
                    .addGroup(background31Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        background31Layout.setVerticalGroup(
            background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background31Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background31Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(background31Layout.createSequentialGroup()
                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(no_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tgl_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background31Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(background21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background31Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(notlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(background23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(background24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(background22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        Gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MasterBarang.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel11.setText("TRANSAKSI PENJUALAN");

        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Keluar.png"))); // NOI18N
        Kembali.setText("KEMBALI");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Gambar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(background31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gambar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(background31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void nama_barangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nama_barangItemStateChanged
        // TODO add your handling code here:
        String kode = (String) nama_barang.getSelectedItem();
        String kodeFix = kode.substring(0, 4);
        try{
            Statement ktB=koneksi.getConnection().createStatement();
            ResultSet rsKBr=ktB.executeQuery("SELECT jumlah, harga FROM barang WHERE kode_barang = '"+kodeFix+"'");
            while (rsKBr.next()){
                stok.setText(rsKBr.getString("jumlah"));
                harga.setText(rsKBr.getString("harga"));
            }
        } catch (SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_nama_barangItemStateChanged

    private void simpanKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKeranjangActionPerformed
        // TODO add your handling code here:
        String kode = (String) nama_barang.getSelectedItem();
        String kodeFix = kode.substring(0, 4);
        String namaBrg = kode.substring(5, kode.length()-0);
            int hrg = Integer.valueOf(harga.getText());
            int jml = Integer.valueOf(jumlah.getText());
            long subTot = hrg * jml;
            
            Object[] data = new Object[5];
            data [0] = kodeFix;
            data [1] = namaBrg;
            data [2] = harga.getText();
            data [3] = jumlah.getText();
            data [4] = subTot;
            
            model.addRow(data);
            this.hitungTotalBayar();
            this.kosongkanData();
    }//GEN-LAST:event_simpanKeranjangActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int delData = tabelTransaksi.getSelectedRow();
        if (delData == -1){
            return;
        }else{
            model.removeRow(delData);
            this.hitungTotalBayar();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTransaksiActionPerformed
        // TODO add your handling code here:
        this.simpanPenjualan();
        this.simpanDetailPenjualan();
        this.kosongkanDataTransaksi();
        btTambahtrans.setEnabled(true);
        model.getDataVector().removeAllElements();;
        model.fireTableDataChanged();
    }//GEN-LAST:event_simpanTransaksiActionPerformed

    private void btTambahtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahtransActionPerformed
        try {
            // TODO add your handling code here:
            this.genFak();
            this.dateNow();
            simpanKeranjang.setEnabled(true);
            simpanTransaksi.setEnabled(true);
            hapus.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(transaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btTambahtransActionPerformed

    private void namaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namaItemStateChanged
        // TODO add your handling code here:
        String id = (String) nama.getSelectedItem();
        String idFix = id.substring(0, 4);
        try{
            Statement ktB=koneksi.getConnection().createStatement();
            ResultSet rsKBr=ktB.executeQuery("SELECT alamat, notelp FROM pelanggan WHERE id_pelanggan ='"+idFix+"'");
                while (rsKBr.next()){
                    alamat.setText(rsKBr.getString("alamat"));
                    notlp.setText(rsKBr.getString("notelp"));
                }
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_namaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                new transaksiView().setVisible(true);
                }catch (SQLException ex){
                    Logger.getLogger(transaksiView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

     // Menampilkan Tanggal dan Jam
    public void dateNow(){
        Date tglCur = new Date();
        SimpleDateFormat frmTgl = new SimpleDateFormat("yyyy-MM-dd");
        String damoye = frmTgl.format(tglCur);
        tgl_penjualan.setText(damoye);
    }
    
    // Menampilkan No_Faktur
    public void genFak() throws SQLException{
        transaksiImplement getUrutan = new transaksiImplement();
        int urutan = getUrutan.urutanDb();
        Date tglJual = new Date();
        SimpleDateFormat formatTgl = new SimpleDateFormat("yyyy-MM-dd");
            String dmy = formatTgl.format(tglJual);
            String KodeAwal = "PO";
            StringBuffer strValues = new StringBuffer();
            strValues.append(KodeAwal);
            strValues.append("-");
            strValues.append(String.valueOf(dmy));
            strValues.append("-");
            strValues.append(String.valueOf(urutan));
            String result = strValues.toString();
            no_faktur.setText(result);
    }
    
    //Menampilkan di combobox Kode_barang
    private void setKodeBarang() throws SQLException{
        transaksiImplement getKdBrg = new transaksiImplement();
        ArrayList<String> urutanArr = getKdBrg.viewKdBrg();
            nama_barang.addItem("== pilih ==");
            for(Object o : urutanArr){
                nama_barang.addItem(o);
            }
    }
    
    //Menampilkan di combobox Kode_Pelanggan
    private void setKodePelanggan() throws SQLException{
        transaksiImplement getKdPlgn = new transaksiImplement();
        ArrayList<String> urutanArr = getKdPlgn.viewKdPlgn();
            nama.addItem("== pilih ==");
            for(Object o : urutanArr){
                nama.addItem(o);
            }
    }
    
    //Mengosongkan data
    private void kosongkanData(){
        jumlah.setText("");
        harga.setText("");
        nama_barang.setSelectedItem("== pilih ==");
        stok.setText("");
    }
    
    
   //Menhitung Total Bayar
    private void hitungTotalBayar(){
        int jmlRow = tabelTransaksi.getRowCount();
        int tot = 0;
        if (jmlRow ==0){
            return;
        }
        else
        {
            for (int i = 0; i< jmlRow; i++){
            int jmlTot = Integer.valueOf((String.valueOf(model.getValueAt(i, 4))));
            tot +=jmlTot;
            }
        }
        totalBayar.setText(String.valueOf(tot));
    }
    
    
   //Simpan Penjualan
    private void simpanPenjualan(){
        String noFaktur = no_faktur.getText();
        String tglJual = tgl_penjualan.getText();
        String idPelanggan = (String) nama.getSelectedItem();
        String idPelangganFix = idPelanggan.substring(0, 4);
        
        if (noFaktur.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Generate No Faktur Gagal / No Faktur kosong");
        }else if (tglJual.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Generate Tanggal Jual Gagal / Tanggal Jual Kosong ");
        }else if (idPelanggan=="== pilih =="){
            JOptionPane.showMessageDialog(null, "Pilih Id Pelanggan Terlebih Dahulu");
        }else{
            
            try{
                PreparedStatement st=koneksi.getConnection().prepareStatement("INSERT INTO penjualan VALUES (?,?,?)");
                    st.setString(1, noFaktur);
                    st.setString(2, tglJual);
                    st.setString(3, idPelangganFix);
                    st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Penjualan Berhasil DI Input");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    // Menyimpan Detail Transaksi Penjualan
        private void simpanDetailPenjualan(){
            int jml = tabelTransaksi.getRowCount();
            if(jml== 0){
                JOptionPane.showMessageDialog(null, "Barang Belum Terpilih");
                return;
            }else
                for (int i = 0; i < jml; i++){
                String noFaktur = no_faktur.getText();
                String kodeBarang = (String) model.getValueAt(i, 0);
                String harga = (String) model.getValueAt(i, 2);
                int jmlbeli = Integer.valueOf(String.valueOf(model.getValueAt(i, 3)));
                System.out.println(kodeBarang);
                try{
                    PreparedStatement st=koneksi.getConnection().prepareStatement("INSERT INTO detail_jual VALUES(?,?,?,?)");
                    st.setString(1, noFaktur);
                    st.setString(2, kodeBarang);
                    st.setString(3,harga);
                    st.setInt(4, jmlbeli);
                    st.executeUpdate();
        }catch (SQLException e){
            e.printStackTrace();
        }
   }
             JOptionPane.showMessageDialog(null, "Data Detail Penjualan Berhasil DI Input");
}
        
    //Mengosonkan Data Taransaksi
        private void kosongkanDataTransaksi(){
            no_faktur.setText("");
            tgl_penjualan.setText("");
            nama.setSelectedItem("== pilih ==");
            alamat.setText("");
            notlp.setText("");
            totalBayar.setText("");
            simpanKeranjang.setEnabled(false);
            hapus.setEnabled(false);
            simpanTransaksi.setEnabled(false);
        }
    

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar;
    private Background.ButtonTransparan Kembali;
    private javax.swing.JTextArea alamat;
    private Background.Background2 background21;
    private Background.Background2 background22;
    private Background.Background2 background23;
    private Background.Background2 background24;
    private Background.Background3 background31;
    private Background.ButtonTransparan btTambahtrans;
    private Background.ButtonTransparan hapus;
    private Background.TextFieldTransparan harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Background.TextFieldTransparan jumlah;
    private javax.swing.JComboBox nama;
    private javax.swing.JComboBox nama_barang;
    private Background.TextFieldTransparan no_faktur;
    private Background.TextFieldTransparan notlp;
    private Background.ButtonTransparan simpanKeranjang;
    private Background.ButtonTransparan simpanTransaksi;
    private Background.TextFieldTransparan stok;
    private javax.swing.JTable tabelTransaksi;
    private Background.TextFieldTransparan tgl_penjualan;
    private Background.TextFieldTransparan totalBayar;
    // End of variables declaration//GEN-END:variables
}