/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;
    import java.sql.SQLException;
    import java.util.logging.Level;
    import java.util.logging.Logger;
    import penjualan.view.barangReport;
    import penjualan.view.barangView;
    import penjualan.view.pelangganReport;
    import penjualan.view.pelangganView;
    import penjualan.view.transaksiView;
    //import sun.rmi.log.LogOutputStream;

/**
 *
 * @author rizkiramdani
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background11 = new Background.Background1();
        background21 = new Background.Background2();
        panelWarnaTransparan1 = new Background.PanelWarnaTransparan();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Login = new Background.ButtonTransparan();
        About = new Background.ButtonTransparan();
        Exit = new Background.ButtonTransparan();
        Home = new Background.ButtonTransparan();
        jLabel3 = new javax.swing.JLabel();
        SIPenjualan = new javax.swing.JMenuBar();
        Master = new javax.swing.JMenu();
        Barang = new javax.swing.JMenuItem();
        Pelanggan = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenu();
        Penjualan = new javax.swing.JMenuItem();
        Pembelian = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        LaporanBarang = new javax.swing.JMenuItem();
        LaporanPelanggan = new javax.swing.JMenuItem();
        LaporanTransaksi = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("S.I.P");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Sistem Informasi Penjualan");

        org.jdesktop.layout.GroupLayout panelWarnaTransparan1Layout = new org.jdesktop.layout.GroupLayout(panelWarnaTransparan1);
        panelWarnaTransparan1.setLayout(panelWarnaTransparan1Layout);
        panelWarnaTransparan1Layout.setHorizontalGroup(
            panelWarnaTransparan1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelWarnaTransparan1Layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .add(panelWarnaTransparan1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelWarnaTransparan1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(217, 217, 217))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelWarnaTransparan1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(117, 117, 117))))
        );
        panelWarnaTransparan1Layout.setVerticalGroup(
            panelWarnaTransparan1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelWarnaTransparan1Layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 23, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout background21Layout = new org.jdesktop.layout.GroupLayout(background21);
        background21.setLayout(background21Layout);
        background21Layout.setHorizontalGroup(
            background21Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(background21Layout.createSequentialGroup()
                .add(174, 174, 174)
                .add(panelWarnaTransparan1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );
        background21Layout.setVerticalGroup(
            background21Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, background21Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(panelWarnaTransparan1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/People.png"))); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About.png"))); // NOI18N
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Home.png"))); // NOI18N
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Java.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout background11Layout = new org.jdesktop.layout.GroupLayout(background11);
        background11.setLayout(background11Layout);
        background11Layout.setHorizontalGroup(
            background11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(background11Layout.createSequentialGroup()
                .add(background11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(background11Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(Home, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(19, 19, 19)
                        .add(Login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(About, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(Exit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(background11Layout.createSequentialGroup()
                        .add(background11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(background11Layout.createSequentialGroup()
                                .add(509, 509, 509)
                                .add(jLabel3))
                            .add(background21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(112, 112, 112)))
                .addContainerGap())
        );
        background11Layout.setVerticalGroup(
            background11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, background11Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(background21, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(361, 361, 361)
                .add(background11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Login, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(About, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Exit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Home, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        SIPenjualan.setBackground(new java.awt.Color(225, 221, 221));
        SIPenjualan.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));

        Master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Master.png"))); // NOI18N
        Master.setText("Master Data");
        Master.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterActionPerformed(evt);
            }
        });

        Barang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        Barang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Barang.png"))); // NOI18N
        Barang.setText("Barang");
        Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangActionPerformed(evt);
            }
        });
        Master.add(Barang);

        Pelanggan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Pelanggan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/People.png"))); // NOI18N
        Pelanggan.setText("Pelanggan");
        Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelangganActionPerformed(evt);
            }
        });
        Master.add(Pelanggan);

        SIPenjualan.add(Master);

        Transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Penjualan.png"))); // NOI18N
        Transaksi.setText("Transaksi");
        Transaksi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        Penjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        Penjualan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Penjualan.png"))); // NOI18N
        Penjualan.setText("Penjualan");
        Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenjualanActionPerformed(evt);
            }
        });
        Transaksi.add(Penjualan);

        Pembelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        Pembelian.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Pembelian.png"))); // NOI18N
        Pembelian.setText("Pembelian");
        Pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembelianActionPerformed(evt);
            }
        });
        Transaksi.add(Pembelian);

        SIPenjualan.add(Transaksi);

        Laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        Laporan.setText("Laporan");
        Laporan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        LaporanBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        LaporanBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LaporanBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Barang.png"))); // NOI18N
        LaporanBarang.setText("Barang");
        LaporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanBarangActionPerformed(evt);
            }
        });
        Laporan.add(LaporanBarang);

        LaporanPelanggan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        LaporanPelanggan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LaporanPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/People.png"))); // NOI18N
        LaporanPelanggan.setText("Pelanggan");
        LaporanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanPelangganActionPerformed(evt);
            }
        });
        Laporan.add(LaporanPelanggan);

        LaporanTransaksi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        LaporanTransaksi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LaporanTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Penjualan.png"))); // NOI18N
        LaporanTransaksi.setText("Transaksi");
        Laporan.add(LaporanTransaksi);

        SIPenjualan.add(Laporan);

        Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Help.png"))); // NOI18N
        Help.setText("Help");
        Help.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SIPenjualan.add(Help);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        SIPenjualan.add(Logout);

        setJMenuBar(SIPenjualan);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(background11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(background11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangActionPerformed
        // TODO add your handling code here:
        barangView tampilBarang = new barangView();
        tampilBarang.setLocationRelativeTo(null);
        tampilBarang.setVisible(true);
    }//GEN-LAST:event_BarangActionPerformed

    private void PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelangganActionPerformed
        // TODO add your handling code here:
        pelangganView tampilPelanggan = new pelangganView();
        tampilPelanggan.setLocationRelativeTo(null);
        tampilPelanggan.setVisible(true);
    }//GEN-LAST:event_PelangganActionPerformed

    private void MasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MasterActionPerformed

    private void PembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembelianActionPerformed
        // TODO add your handling code here:
        try {  
            transaksiView trans = new transaksiView();
            trans.setLocationRelativeTo(null);
            trans.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PembelianActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        MenuUtama Masuk = new MenuUtama();
        Masuk.setLocationRelativeTo(null);
        Masuk.setVisible(true);
    }//GEN-LAST:event_HomeActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit (0);
    }//GEN-LAST:event_ExitActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutActionPerformed

    private void PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenjualanActionPerformed
        // TODO add your handling code here:
        try {  
            transaksiView trans = new transaksiView();
            trans.setLocationRelativeTo(null);
            trans.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PenjualanActionPerformed

    private void LaporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanBarangActionPerformed
        // TODO add your handling code here:
        barangReport Masuk = new barangReport();
        Masuk.setLocationRelativeTo(null);
        Masuk.setVisible(true);
    }//GEN-LAST:event_LaporanBarangActionPerformed

    private void LaporanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanPelangganActionPerformed
        // TODO add your handling code here:
        pelangganReport Masuk = new pelangganReport();
        Masuk.setLocationRelativeTo(null);
        Masuk.setVisible(true);
    }//GEN-LAST:event_LaporanPelangganActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Background.ButtonTransparan About;
    private javax.swing.JMenuItem Barang;
    private Background.ButtonTransparan Exit;
    private javax.swing.JMenu Help;
    private Background.ButtonTransparan Home;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem LaporanBarang;
    private javax.swing.JMenuItem LaporanPelanggan;
    private javax.swing.JMenuItem LaporanTransaksi;
    private Background.ButtonTransparan Login;
    private javax.swing.JMenu Logout;
    private javax.swing.JMenu Master;
    private javax.swing.JMenuItem Pelanggan;
    private javax.swing.JMenuItem Pembelian;
    private javax.swing.JMenuItem Penjualan;
    private javax.swing.JMenuBar SIPenjualan;
    private javax.swing.JMenu Transaksi;
    private Background.Background1 background11;
    private Background.Background2 background21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private Background.PanelWarnaTransparan panelWarnaTransparan1;
    // End of variables declaration//GEN-END:variables
}